apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: whalesay
spec:
  arguments: {}
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      args:
      - Hello World
      command:
      - cowsay
      image: docker/whalesay
      name: ""
      resources: {}
